### ISSUE TITLE
Demo python scripts showing how to load and visualize annotations

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#108]

**Comment by DavidZhang73** [comment]
About visualization, since all we have is the `annotation.json`, does it mean only visualizing annotations without the video frame in the background?

**Comment by sgould** [comment]
The demo script can either operate on downloaded keyframes or assume the video is available. The main goal is to provide example code to show how the annotations can be read into Python (and how they relate to the image, so should produce meaningful visualizations).
