### ISSUE TITLE
Doesn't render video properly when loading annotations from url query

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#109]
Attempting to load video, config and annotations at the same time fails to render the video frames (on Windows, Chrome). Try:
http://users.cecs.anu.edu.au/~sgould/vidat/?video=needinput.mp4&config=needinputconfig.json&annotation=needinput.json

**Comment by DavidZhang73** [comment]
Commit https://github.com/anucvml/vidat/issues/109 fixed keyframe panel not rendering issue, however, the video on my laptop works well. 

More tests ongoing.

**Comment by DavidZhang73** [comment]
BTW, when both annotation and config are set in URL, only annotation will be loaded. That is because the configurations are also stored in annotation file. If config is loaded, it can mismatch with configurations used by annotations.

**Comment by sgould** [comment]
Works now on my setup.

On the annotation versus configuration point, there may be situations where we have an already annotated video, say with objects, and would like to start labelling new objects or activities which are not already in the configuration. I'm not sure of the best way to do this but perhaps loading a configuration (manually) after the video is loaded will work in this case.

**Comment by DavidZhang73** [comment]
The reason why they cannot be loaded at the same time is the configuration in `annotation.json` is matched with annotations. For example, the skeleton annotation's type is defined in that configuration. If that type is `not stored` in the config.json or is something else in fact, then some errors would occur. So, the best solution for the scenario you descripted, should be a conflict solver when manually load `config.json` in Configuration page.

Or, we can split configuration out from `annotation.json`. Making it two independent files, one `annotation.json`, contains only annotations and one `config.json,` contains only configurations. But it will increase the danger of mismatching and complexity of maintenance.

**Comment by DavidZhang73** [comment]
Should work now.
