### ISSUE TITLE
Tablet mode operator modifiers

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#120]
The operation modifiers for tablet mode operation also appear in desktop mode but have no effect. They only work in tablet mode. We should make them invisible in desktop mode.

Also, is there a way to switch between tablet and desktop mode (e.g., if the browser is detected as tablet but the user has a keyboard connected)?

**Comment by DavidZhang73** [comment]
> The operation modifiers for tablet mode operation also appear in desktop mode but have no effect. They only work in tablet mode. We should make them invisible in desktop mode.

The detection is based on whether the device has a touch capable screen. [`Platform.has.touch`](https://quasar.dev/options/platform-detection#Properties). And the events for mouse and touch are different, hence those mode operations have no effect using mouse.

> Also, is there a way to switch between tablet and desktop mode (e.g., if the browser is detected as tablet but the user has a keyboard connected)?

- [ ] Add a new option `touch` to preferences, with default `Platform.has.touch`.
- [ ] Add the `touch` to URL Parameters.
- [ ] Add a popup when using mouse in touch mode and touching in mouse mode.

**Comment by sgould** [comment]
Ah, okay. I think this is because my laptop also has a touch screen. On my desktop the modifiers are not visible. No need to fix (but maybe add a comment on the help page that modifier switches will show for devices with touchscreens).
