### ISSUE TITLE
Single frame advance

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#121]
Operation of single frame advance (left and right arrows) are still a bit counterintuitive and doesn't always work. For example, its not clear (i.e., there is no visual indication) whether pressing the arrow keys will advance the left frame, the right frame or both frames. The behaviour seems to be whichever frame (or both) were last selected. But this doesn't always work. A visual indicator, or separate shortcut keys for left frame, right frame and both frames may be a better solution.

**Comment by DavidZhang73** [comment]
Yeah, this is related to https://github.com/anucvml/vidat/issues/79#issuecomment-688180309.

Put it simple, the focus mechanism is not implemented by the component I use. Instead, I simulate focus state manually, making it a little bit counterintuitive.

I will add some visual indicator to it. e.g., only the focused one will have the tooltip on the slider.

**Comment by sgould** [comment]
This is a good solution, the visual indicator really helps. A further improvement could be to add a shortcut key to cycle between focus. Say, pressing up arrow moves from the current focus to the next focus (going clockwise from 'left' to 'right' to 'range'). Pressing down arrow moves the focus the other way ('range' to 'right' to 'left' to 'range', ...). This will help when using the keyboard to fine tune the frames.
