### ISSUE TITLE
Adding objects with popup disabled label dropdown does not have focus

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#122]
When adding a new object with "Show popup" disabled, the label drop-down list shows but does not have focus so does not respond to keyboard presses (e.g., arrows, enter, or first letters of label). The drop-down list should get the focus after an object is added. Note that the behaviour for adding regions is correct.

**Comment by DavidZhang73** [comment]
This is related to 7937c46d361737468692ec0c485c0062e1638156, which adds focus functionality to the canvas element.

When mouse down, up, over, out, enter event emits, canvas will be focused. This is designed to get focus from other elements (like the mode selector in the middle), when drawing objects with key pressed.

To solve the bug mentioned, just make the canvas focused only when mouse down emits.
