### ISSUE TITLE
Controlling threshold to anchor point in tablet mode

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#125]
In tablet mode it's sometimes difficult to tap and drag an anchor point or box edge (often inserting a new object instead). It would be nice to have a user configurable preference setting for the threshold in tablet mode.

**Comment by DavidZhang73** [comment]
You might need to clear browser cache.

**Comment by sgould** [comment]
Even after clearing the browser cache the preferences are stored in localStorage, which may not clear and are therefore missing. When we add preferences is the tool cannot find them in localStorage we should populate with the default.
