### ISSUE TITLE
Importing video with its audio component

### ISSUE THREAD

**Issue by KhaledSaleh** [anucvml/vidat#128]
Hello. Thanks for this fantastic annotation tool, I found it really useful in my research. 

I wonder if it's possible to playback the loaded video inside the tool with its audio as well? I believe this feature would be beneficial for many behavioral annotation tasks if it's supported.

Thanks once again and keep up the good work.

**Comment by sgould** [comment]
Thanks for the suggestion. We have no current plans for including audio but may consider it for a future enhancement or happy to take a pull request.

**Comment by DavidZhang73** [comment]
> I wonder if it's possible to playback the loaded video inside the tool with its audio as well? I believe this feature would be beneficial for many behavioral annotation tasks if it's supported.

@KhaledSaleh This is quite a simple feature actually. When playing the video, there is an independent video element on top of the canvas element. So, just delete the `muted` attribute of that element should work.

https://github.com/anucvml/vidat/blob/95dc8ba1afe831db521ba6a1a35f6fa7f8fa3eec/src/js/pages/annotation/components/videoPlayer.js#L7

@sgould Are we going to keep it muted or unmuted or provide an option (preference and URL parameter) for that?

**Comment by KhaledSaleh** [comment]
@sgould Thanks for your reply

@DavidZhang73 Thanks, I have removed the 'muted' attribute and it works flawlessly 👍

**Comment by sgould** [comment]
@DavidZhang73 Cool, that was easy. Yes, let's include a user preference for playing video with audio.
