### ISSUE TITLE
在浏览器上测试，发下无法加载MP4

### ISSUE THREAD

**Issue by qiuzhizhe** [anucvml/vidat#135]

**Comment by DavidZhang73** [comment]
你好，你是用的v1还是v2版本的Vidat？
无法加载是报错了嘛，能提供console的报错信息嘛？

---
Hi, which version of Vidat are you using?
Is there any error message, if so, could you please provide the error message?

**Comment by qiuzhizhe** [comment]
v2版本，可以加载代码自带的视频，无法加载自己采集的MP4视频，自己采集的需要转码处理吗？

**Comment by qiuzhizhe** [comment]
> 你好，你是用的v1还是v2版本的Vidat？ 无法加载是报错了嘛，能提供console的报错信息嘛？
> 
> Hi, which version of Vidat are you using? Is there any error message, if so, could you please provide the error message?
v2版，加载自己的mp4视频，包如下措：这个需要转码处理吗？
ould not load video: blob:https://vidat2.davidz.cn/6f3f3be8-ca53-4814-8654-7d3cb749ce5f:

**Comment by DavidZhang73** [comment]
@qiuzhizhe 
能提供一个mp4样例给我调试嘛？

---

Could you provide an mp4 example for debugging?

**Comment by DavidZhang73** [comment]
Close because no response.
