### ISSUE TITLE
你好，你是用的v1还是v2版本的Vidat？

### ISSUE THREAD

**Issue by qiuzhizhe** [anucvml/vidat#147]
你好，你是用的v1还是v2版本的Vidat？
无法加载是报错了嘛，能提供console的报错信息嘛？

---
Hi, which version of Vidat are you using?
Is there any error message, if so, could you please provide the error message?

_Originally posted by @DavidZhang73 in https://github.com/anucvml/vidat/issues/135#issuecomment-1055247352_

**Comment by DavidZhang73** [comment]
https://github.com/anucvml/vidat/issues/135#issuecomment-1055247352
