### ISSUE TITLE
Submission notify

### ISSUE THREAD

**Issue by DavidZhang73** [anucvml/vidat#154]
Feedback from Itzik: If its possible I think the submission code should appear at the center of the screen and not disappear, just stay. It was easy to miss even though I expected it and I am not sure what happens if I missed it and am now looking for it (Is there an option to retrieve it after submission?.

**Comment by sgould** [comment]
An alternative solution here is to have an option to show a console of logged messages. This would then also be useful for referring back to an error after a video is loaded and other status/warning messages that may be missed.

**Comment by DavidZhang73** [comment]
@sgould good idea, but the option seems dispensable, since normal users would not bother toggling it on, and when some bugs occur, it is intuitive to open the console panel to find out what happen. Maybe, just log a message whenever there is a notification, or an error occurred?
