### ISSUE TITLE
Unable to load H265-compressed video

### ISSUE THREAD

**Issue by vineetparikh** [anucvml/vidat#175]
Hi there,

I compressed a video (using FFMPEG) with the H265 codec so it would use up less memory before uploading to one of the hosts for annotation (that way there's less strain on your end). The video plays properly, but it cannot be read by Vidat on the first host. Any idea as to what might be going on here?

Thanks,
Vineet

**Comment by vineetparikh** [comment]
(For context this works with H264 codec, so I think it's just a matter of supporting the new codec)

**Comment by DavidZhang73** [comment]
Hi Vinnet,

> I compressed a video (using FFMPEG) with the H265 codec so it would use up less memory before uploading to one of the hosts for annotation (that way there's less strain on your end)

At present, there is no workload on my server regarding video processing. The Vidat tool is a frontend-only application that operates entirely within the browser on your computer. Thus, there is no necessity to compress the video using h265 to save memory. In fact, doing so could potentially decrease the performance of your computer.

As for the h265 codec, I managed to have a hotfix on that, can you have a try on the [second host](https://vidat2.davidz.cn/)?

**Comment by vineetparikh** [comment]
oddly enough I'm getting `Could not load the video: InvalidStateError: Failed to execute 'decode' on 'VideoDecoder': Cannot call 'decode' on a closed codec.` when attempting to run on the second host (using Chrome on Ubuntu).

**Comment by DavidZhang73** [comment]
Can you provide the version of the chrome you are using and, if possible, the h265 encoded mp4 file?

**Comment by vineetparikh** [comment]
hey! just wanted to close the loop on this, i just ended up using h264 for everything instead. thanks again for looking into this!
