### ISSUE TITLE
Failed to upload the annotation file created by myself.

### ISSUE THREAD

**Issue by zhousheng97** [anucvml/vidat#181]
Hi, I tried to create the annotation json file myself and upload it to Vidat's webpage instead of re-uploading the file downloaded from the site. But the lower right corner of the page appears a red pop-up window, an error message as follows: "**TypeError: Cannot read properties of undefined (reading 'length ')**", how to solve? 

The contents of the json file are as follows: 
`{"version": "2.0.3", "annotation": {"video": {"src": "blob:http://localhost:8088/5122b0ac-9a20-4559-b827-03252ece3279", "duration": 6.7, "fps": 10.0, "frames": 67, "height": 716, "width": 1280}, "keyframelist": [0, 10, 20, 30, 40, 50, 60], "objectAnnotationListMap": {"57": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 844.6448973661363, "y": 650.2049028303284, "width": 150.10449237710236, "height": 48.18180810887452}], "58": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 844.749812855217, "y": 650.1506483784123, "width": 150.01606032472228, "height": 48.25961632911299}], "59": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 844.494538012289, "y": 650.1663281161115, "width": 150.27239858479697, "height": 48.24113527168333}], "60": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 844.7236935545229, "y": 650.5170743781184, "width": 150.0145879886104, "height": 47.825531419544404}], "61": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 844.6509433688761, "y": 650.4069325433277, "width": 150.10717087943522, "height": 47.99625454225088}], "62": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 845.0393644730682, "y": 650.5987701989236, "width": 149.40125152261362, "height": 47.853118781840294}], "63": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 845.3068946338867, "y": 650.6095110536514, "width": 149.12296610332032, "height": 47.74557750207214}], "64": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 845.2653405125004, "y": 650.5848318769443, "width": 149.11580334999917, "height": 47.8244768711113}], "65": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 845.2681843994585, "y": 650.6905519609764, "width": 149.12702231436424, "height": 47.62005574601585}], "66": [{"highlight": false, "instance": 1, "score": null, "labelId": 0, "color": "#00FF00", "x": 845.3849696421669, "y": 650.7768346059681, "width": 148.9906197976975, "height": 47.54453635446998}]}, "regionAnnotationListMap": {}, "skeletonAnnotationListMap": {}, "actionAnnotationList": []}, "config": {"objectLabelData": [{"color": "#00FF00", "id": 0, "name": "default"}], "actionLabelData": [{"color": "#0000FF", "id": 0, "name": "default", "objects": [0]}], "skeletonTypeData": []}}`

**Comment by DavidZhang73** [comment]
Hi @zhousheng97, could you please also upload the example video?

**Comment by zhousheng97** [comment]
Thanks for your prompt reply, you can test this video and annotate file pairs.

https://github.com/anucvml/vidat/assets/30627142/2572dda2-fdc1-4b5d-9fcc-947d30ee3a75

[q_id_13463.json](https://github.com/anucvml/vidat/files/13346804/q_id_13463.json)

**Comment by DavidZhang73** [comment]
Hi @zhousheng97, I've tested what you just sent to me. It is a typo, `keyframelist` -> `keyframeList`.

**Comment by zhousheng97** [comment]
> Hi @zhousheng97, could you please also upload the example video?
> 
> Found one typo, all keys are case-sensitive, hence `keyframelist` -> `keyframeList`.

Thank you very much. After modification, the problem has been solved!
