### ISSUE TITLE
Could not load the video: AbortError: BodyStreamBuffer was aborted

### ISSUE THREAD

**Issue by zhousheng97** [anucvml/vidat#183]
What is the reason for the error "Could not load the video: AbortError: BodyStreamBuffer was aborted" when uploading a video to the web page? How to solve it?

**Comment by DavidZhang73** [comment]
Hi @zhousheng97，I should have just fixed this #182 in version 2.0.4. Could you please double check the version you were using? If you're using the latest one, please send me one example video and may I know which browser are you using?

**Comment by zhousheng97** [comment]
> Hi @zhousheng97，I should have just fixed this #182 in version 2.0.4. Could you please double check the version you were using? If you're using the latest one, please send me one example video and may I know which browser are you using?

Sorry, I did not notice the update of the version, I have changed the new version, there is no problem at present, thank you very much!
