### ISSUE TITLE
Error when running backend example

### ISSUE THREAD

**Issue by mhayoz** [anucvml/vidat#191]
Hi

I wanted to run the backend example following the instructions in tools/backend/README.md. However, I get the following error when clicking on a video to annotate: Cannot GET /vidat/ 
Any idea how I can fix this?

Thank you in advance for your help

**Comment by DavidZhang73** [comment]
Hi,

The backend part was developed for Vidat version 1 as a prove of concept. The vidat frontend (for v2, this should be the built statistics, i.e., in `dist`) should be put into the root folder of the backend for convenience. I've updated the [doc](https://github.com/DavidZhang73/vidat/tree/main/tools/backend#installation). Please try it and let me know if anything goes wrong again.

**Comment by mhayoz** [comment]
That fixed it. Thanks!
