### ISSUE TITLE
Amazon Mechanical Turk platform

### ISSUE THREAD

**Issue by DavidZhang73** [anucvml/vidat#37]
I certainly believe that the current prototype of the annotation tool covers or will cover (after some iterations) everything that we need for doing the spatial, temporal, and natural-language annotation for the research on video analysis. However, I would like to point out some things about the use of this tool in the Amazon Mechanical Turk platform.

It is important to consider the annotation tool for two purposes. Of course, the annotation process itself and the evaluation of the annotators. Turkers want to get their payment as soon as they can. They want to receive their payment between two or three days. If we want to assess the annotations in time. We need a tool that facilitates the evaluation of annotations and annotators. It is for that reason that I believe this tool should have two purposes in mind.

**Comment by sgould** [comment]
Submit command can be provided in configuration (or as url query) for maximum extensibility (e.g., post annotation json to webserver).
