### ISSUE TITLE
Editing region (polygon) points

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#71]
We need a method to add and delete points from a polygon region. This can be holding down "shift" while clicking to add a new point and holding down "ctrl" or "alt" while clicking to delete. On a tablet it would have to involve a different editing mode, e.g., "region (edit)" which does not add new regions but adds and deletes existing points. Delete is disabled if there are <= 3 points remaining.

**Comment by sgould** [comment]
How are polygon points added or deleted in tablet mode for an existing polygon?

**Comment by DavidZhang73** [comment]
![region](https://user-images.githubusercontent.com/33928385/110882611-35830000-831d-11eb-8f30-30090eff407a.gif)
